class_path: benchmarks.experiments.synth_data_generation.pipeline.models.biodiffusion.BioDiffusion
init_args: 
  model:
    class_path: benchmarks.experiments.synth_data_generation.pipeline.models.unet1d.Unet1D_cls_free
    init_args:
      dim: 32
      num_classes: 6
      channels: 6
  synth_data_path: "./benchmarks/experiments/synth_data_generation/pipeline/data/synth/biodiffusion_norm_label_yaml"
  noise_steps: 1000
  schedule_type: 'cosine'
  beta_start: 1e-4
  beta_end: 0.02
  n_timesteps: 60
  lr: 3e-4
  conditional: True
  channels: 6
  signal_padding: 4
